### ISSUE TITLE
cssmodule如何优雅编写样式覆盖？

### ISSUE THREAD

**Issue by yangbin1994** [dvajs/dva#1170]
```less
:global {
    .hotmap-heatmap--left__heat-view_hide-share {
        .share-html {
            display: none;
        }
    }
    .hotmap-heatmap--left__heat-view_hide-jump {
        .jump-html {
            display: none;
        }
    }
}

.left {
    display: flex;
    justify-content: center;
    flex-direction: column;
    align-items: center;
}

.left__tip-msg {
    text-align: center;
    padding: 2px 8px !important;
}

.left__heat-view {
    margin-top: 20px;
}

.right {
    display: flex;
    justify-content: center;
    flex-direction: column;
    align-items: center;
}

.right__mode-switch {
    margin-bottom: 10px;
    min-height: 40px;
}

.right__iphone-6 {
    position: relative;
    width: 355px;
    height: 667px;
}

.right__tooltip {
    position: absolute;
    top: 5px;
    right: 5px;
}

.right__in-iframe {
    border: 1px solid rgb(244, 244, 244);
    width: 100%;
    height: 100%;
}

```
我现在是上述方式，但是如果继续这样的写法，我更倾向于将cssmodule禁用，全部使用硬编码的命名空间前缀，类似`hotmap-heatmap--xxx`。
有更好的样式编写方式吗？希望大牛抽空给些建议，十分感谢thx O(∩_∩)O
