### ISSUE TITLE
css-modules 编译问题

### ISSUE THREAD

**Issue by linkeo** [dvajs/dva#333]
在使用keyframes时发现css-modules出现如下问题：

原始css代码：

```css
@keyframes rotating {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.rotating-item {
  animation: 5s linear 0 infinite rotating;
}
```

编译成了如下代码：

```css

@-webkit-keyframes rotating___3vsQl {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}
@keyframes rotating___3vsQl {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}
.rotating-item___3pALh {
  -webkit-animation: 5s linear 0 infinite :local(rotating);
          animation: 5s linear 0 infinite :local(rotating);
}
```

我觉得正确的应该是：

```css

@-webkit-keyframes rotating___3vsQl {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}
@keyframes rotating___3vsQl {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}
.rotating-item___3pALh {
  -webkit-animation: 5s linear 0 infinite rotating___3vsQl;
          animation: 5s linear 0 infinite rotating___3vsQl;
}
```

不知道是css-modules的bug还是webpack里的配置问题。

>   注：
>
>   -   用dva-cli创建的项目，没修改webpack配置。
>   -   刚开始用less写的，后来改成css也不行。
>   -   less写的情况下 注明 `@keyframes :global(rotating)` 会报错
>
>   各工具版本如下：
>
>   -   node.js@6.9.0
>   -   dva@1.1.0
>   -   atool-build@0.9.2
>   -   webpack@1.12.15
>   -   postcss-modules-extract-imports@1.0.1
>   -   postcss-modules-local-by-default@1.1.1
>   -   postcss-modules-scope@1.0.2
>   -   postcss-modules-values@1.2.2
