### ISSUE TITLE
关于className的问题

### ISSUE THREAD

**Issue by cpu220** [dvajs/dva#983]
我在less里写了一个动画
``` less
/*声明*/
@-webkit-keyframes 'aaa'{}
 /* 引用部分 */
animation: aaa 1s; 
```
---

现在的问题是，
工程会将代码变成
``` less
/*声明*/
@-webkit-keyframes -'aaa'-_xxxxx{}
 /* 然后引用部分 */
animation: aaa____1hLA1 1s; 
```
于是，声明的动画name，和使用的不是同一个，所以效果无法出来，就算用了less变量，也无效，求问怎么破？还是在工程的哪个配置里做修改？
